package com.lf.sci.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setSerialId(java.lang.String serialId) {
		set("serial_id", serialId);
		return (M)this;
	}

	public java.lang.String getSerialId() {
		return getStr("serial_id");
	}

	public M setUserNo(java.lang.String userNo) {
		set("user_no", userNo);
		return (M)this;
	}

	public java.lang.String getUserNo() {
		return getStr("user_no");
	}

	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}

	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	public M setUserPwd(java.lang.String userPwd) {
		set("user_pwd", userPwd);
		return (M)this;
	}

	public java.lang.String getUserPwd() {
		return getStr("user_pwd");
	}

	public M setRoleNo(java.lang.String roleNo) {
		set("role_no", roleNo);
		return (M)this;
	}

	public java.lang.String getRoleNo() {
		return getStr("role_no");
	}

	public M setUserRights(java.lang.String userRights) {
		set("user_rights", userRights);
		return (M)this;
	}

	public java.lang.String getUserRights() {
		return getStr("user_rights");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}

	public java.lang.String getCreateUser() {
		return getStr("create_user");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

	public M setUpdateUser(java.lang.String updateUser) {
		set("update_user", updateUser);
		return (M)this;
	}

	public java.lang.String getUpdateUser() {
		return getStr("update_user");
	}

	public M setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.lang.String getUpdateTime() {
		return getStr("update_time");
	}

	public M setIsDelete(java.lang.String isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.String getIsDelete() {
		return getStr("is_delete");
	}

}
