package com.lf.sci.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public M setSerialId(java.lang.String serialId) {
		set("serial_id", serialId);
		return (M)this;
	}

	public java.lang.String getSerialId() {
		return getStr("serial_id");
	}

	public M setMenuNo(java.lang.String menuNo) {
		set("menu_no", menuNo);
		return (M)this;
	}

	public java.lang.String getMenuNo() {
		return getStr("menu_no");
	}

	public M setMenuName(java.lang.String menuName) {
		set("menu_name", menuName);
		return (M)this;
	}

	public java.lang.String getMenuName() {
		return getStr("menu_name");
	}

	public M setMenuUrl(java.lang.String menuUrl) {
		set("menu_url", menuUrl);
		return (M)this;
	}

	public java.lang.String getMenuUrl() {
		return getStr("menu_url");
	}

	public M setMenuParentNo(java.lang.String menuParentNo) {
		set("menu_parent_no", menuParentNo);
		return (M)this;
	}

	public java.lang.String getMenuParentNo() {
		return getStr("menu_parent_no");
	}

	public M setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.lang.String getCreateTime() {
		return getStr("create_time");
	}

	public M setUpdateTime(java.lang.String updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.lang.String getUpdateTime() {
		return getStr("update_time");
	}

	public M setIsDelete(java.lang.String isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public java.lang.String getIsDelete() {
		return getStr("is_delete");
	}

}
